language: python
python: 2.7
install:
  - pip install tox pytest-cov pep8
script:
  # run tests in different python versions with tox
  # and run pep8
  - python setup.py test
  # for coverage
  - pip install -e .
  - py.test
